spring:
    datasource:
        url: jdbc:mysql://localhost:3306/authentication
        username: root
        password: any
        driver-class-name: com.mysql.cj.jdbc.Driver
    mail:
        host: smtp.gmail.com
        port: 587
        username: exmpel@gmail.com
        password: anyany
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
            mail.debug: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
